version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: awakecup
      MYSQL_ROOT_PASSWORD: YourPassword123
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - awakecup-network

  backend:
    image: kiin04/awakecup-backend:latest
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=awakecup;Uid=root;Pwd=YourPassword123;
    depends_on:
      - db
    networks:
      - awakecup-network

  admin-ui:
    image: kiin04/awakecup-admin:latest
    ports:
      - "3000:80"
    networks:
      - awakecup-network

  store-ui:
    image: kiin04/awakecup-store:latest
    ports:
      - "3001:80"
    networks:
      - awakecup-network

networks:
  awakecup-network:
    driver: bridge
