version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USER}/awakecup-backend:latest
    container_name: awakecup-backend-1
    ports:
      - "5000:5000"
    volumes:
      - ./appdata:/app/wwwroot/appdata
    environment:
      - App__ConnectionString=Server=${DB_HOST};Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASS};CharSet=utf8mb4;
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - awakecup-network

  admin-ui:
    image: ${DOCKER_HUB_USER}/awakecup-admin:latest
    ports:
      - "3000:80"
    networks:
      - awakecup-network

  store-ui:
    image: ${DOCKER_HUB_USER}/awakecup-store:latest
    ports:
      - "3001:80"
    networks:
      - awakecup-network

networks:
  awakecup-network:
    driver: bridge
